cp -r ~/.config/nushell/*.nu ./nushell
cp -r ~/.config/alacritty .
cp -r ~/.config/helix .
cp -r ~/.config/sway .
cp -r ~/.config/waybar .
cp -r ~/.config/fuzzel .
cp -r ~/.config/mako .
cp -r ~/Pictures/Wallpapers/* ./wallpapers
cp -r ~/scripts .