theme = "gruvbox"

[editor]
mouse = true
auto-format = true
cursorline = true
line-number = "relative"
idle-timeout = 0
completion-trigger-len = 1
# completion-replace = true
color-modes = true
true-color=true 
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]
rulers = [80]

[editor.file-picker]
hidden = false
git-ignore = false

[editor.indent-guides]
render = true
character = "│"
skip-levels = 1

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.lsp]
display-messages = true
display-inlay-hints = true
snippets = false

[editor.statusline]
left = ["mode", "separator", "diagnostics", "file-name", "file-modification-indicator"]
center = []
right = ["position", "file-encoding", "file-line-ending", "file-type"]
separator = " "
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

# [keys.normal]
# left = []
# right = []
# up = []
# down = []

# [keys.insert]
# left = []
# right = []
# up = []
# down = []

# [keys.select]
# left = []
# right = []
# up = []
# down = []
