theme = "gruvbox"

[editor]
auto-format = true
true-color = true
cursorline = true
idle-timeout = 0
completion-trigger-len = 1
color-modes = true
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]

[editor.file-picker]
hidden = false
git-ignore = false

[editor.indent-guides]
render = true
character = "│"
skip-levels = 1

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.lsp]
display-messages = true
display-inlay-hints = true
snippets = false

[editor.statusline]
left = ["mode", "separator", "diagnostics", "file-name", "file-modification-indicator"]
center = []
right = ["position", "file-encoding", "file-line-ending", "file-type"]
separator = " "
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]