[[language]]
name = "rust"
auto-format = true

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'

[[language]]
name = "cpp"
indent = { tab-width = 4, unit = "    " }
auto-format = true

[[language]]
name = "c"
indent = { tab-width = 4, unit = "    " }
auto-format = true