"attribute" = "aqua2"
"keyword" = { fg = "red2" }
"keyword.directive" = "aqua1"
"namespace" = "aqua2"
"punctuation" = "orange2"
"punctuation.delimiter" = "orange2"
"operator" = "purple2"
"special" = "purple0"
"variable.other.member" = "blue2"
"variable" = "light2"
"variable.builtin" = "orange2"
"variable.parameter" = "light2"
"type" = "yellow2"
"type.builtin" = "yellow2"
"constructor" = { fg = "purple2", modifiers = ["bold"] }
"function" = { fg = "green2", modifiers = ["bold"] }
"function.macro" = "aqua2"
"function.builtin" = "yellow2"
"tag" = "red2"
"comment" = { fg = "gray1" }
"constant" = { fg = "purple2" }
"constant.builtin" = { fg = "purple2", modifiers = ["bold"] }
"string" = "green2"
"constant.numeric" = "purple2"
"constant.character.escape" = { fg = "light2", modifiers = ["bold"] }
"label" = "aqua2"
"module" = "aqua2"

"diff.plus" = "green2"
"diff.delta" = "orange2"
"diff.minus" = "red2"

"warning" = "orange2"
"error" = "red2"
"info" = "aqua2"
"hint" = "blue2"

# "ui.background" = { bg = "dark0" }
"ui.linenr" = { fg = "dark4" }
"ui.linenr.selected" = { fg = "yellow2" }
"ui.cursorline" = { bg = "dark1" }
"ui.statusline" = { fg = "light1", bg = "dark2" }
"ui.statusline.normal" = { fg = "light1", bg = "dark2" }
"ui.statusline.insert" = { fg = "light1", bg = "aqua1" }
"ui.statusline.select" = { fg = "light1", bg = "orange1" }
"ui.statusline.inactive" = { fg = "light4", bg = "dark1" }
"ui.popup" = { bg = "dark1" }
"ui.window" = { bg = "dark1" }
"ui.help" = { bg = "dark1", fg = "light1" }
"ui.text" = { fg = "light4" }
"ui.text.focus" = { fg = "light1" }
"ui.selection" = { bg = "dark2" }
"ui.selection.primary" = { bg = "dark3" }
"ui.cursor.primary" = { bg = "light4", fg = "dark1" }
"ui.cursor.match" = { bg = "dark3" }
"ui.menu" = { fg = "light1", bg = "dark2" }
"ui.menu.selected" = { fg = "dark2", bg = "blue2", modifiers = ["bold"] }
"ui.virtual.whitespace" = "dark2"
"ui.virtual.ruler" = { bg = "dark1" }
"ui.virtual.inlay-hint" = { fg = "dark4" }
"ui.virtual.wrap" = { fg = "dark2" }

"diagnostic.warning" = { underline = { color = "orange0", style = "curl" } }
"diagnostic.error" = { underline = { color = "red2", style = "curl" } }
"diagnostic.info" = { underline = { color = "aqua2", style = "curl" } }
"diagnostic.hint" = { underline = { color = "blue2", style = "curl" } }

"markup.heading" = "aqua2"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "green2", modifiers = ["underlined"] }
"markup.link.text" = "red2"
"markup.raw" = "red2"

[palette]
dark0_hard  = "#1d2021"
dark0       = "#282828"
dark0_soft  = "#32302f"
dark1       = "#3c3836"
dark2       = "#504945"
dark3       = "#665c54"
dark4       = "#7c6f64"
dark4_256   = "#7c6f64"

gray_245    = "#928374"
gray_244    = "#928374"

light0_hard = "#f9f5d7"
light0      = "#fbf1c7"
light0_soft = "#f2e5bc"
light1      = "#ebdbb2"
light2      = "#d5c4a1"
light3      = "#bdae93"
light4      = "#a89984"
light4_256  = "#a89984"

red1    = "#cc241d"
green1  = "#98971a" 
yellow1 = "#d79921" 
blue1   = "#458588" 
purple1 = "#b16286" 
aqua1   = "#689d6a" 
orange1 = "#d65d0e" 

red0    = "#9d0006" 
green0  = "#79740e" 
yellow0 = "#b57614" 
blue0   = "#076678" 
purple0 = "#8f3f71" 
aqua0   = "#427b58" 
orange0 = "#af3a03" 

red2    = "#fb4934" 
green2  = "#b8bb26" 
yellow2 = "#fabd2f" 
blue2   = "#83a598" 
purple2 = "#d3869b" 
aqua2   = "#8ec07c" 
orange2 = "#fe8019" 
