monitor=eDP-1, 1920x1200, 0x0, 1
# monitor=HDMI-A-1, 1920x1080, 1920x0, 1

$wallpaper = $HOME/Pictures/Wallpapers/sword.jpg
$launcher = fuzzel
$terminal = foot
$bar = waybar

# Startup apps
exec-once = LC_TIME=en_GB.utf8 $bar
exec-once = mako
exec-once = swaybg -i $wallpaper -o \* -m fill
exec-once = wl-paste --type text --watch clipman store
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = hyprctl setcursscale: 1.5,or capitaine-cursors 32
exec-once = ~/.config/hypr/scripts/idle
exec-once = systemctl --user import-environment XDG_CURRENT_DESKTOP XDG_SESSION_TYPE
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

source=~/.config/hypr/env.conf
source=~/.config/hypr/rules.conf
source=~/.config/hypr/keybinds.conf

gesture = 3, horizontal, scale: 0.5, workspace

input {
    kb_layout = us,ru
	kb_options = grp:alt_shift_toggle
    numlock_by_default = true

    follow_mouse = 2
    float_switch_override_focus = 0

    accel_profile = flat
    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    scroll_factor = 1

    touchpad {
        natural_scroll = yes
        scroll_factor = 0.5
        disable_while_typing = yes
    }
}

device {
    name = ftcs1000:00-2808:0105-touchpad
    sensitivity = 0.8
}

general {
    gaps_in = 0
    gaps_out = 0
    border_size = 1
    col.active_border = rgba(d8d8d8cc)
    col.inactive_border = rgba(0f0f0fcc)

    layout = dwindle
}

decoration {
    rounding = 0

    blur {
      enabled = false
    }
}

animations {
    enabled = false

    bezier=linear, 0, 0.25, 0.75, 1
    bezier=easeInOut, 0.42, 0, 0.58, 1
    bezier=easeIn, 0, 0.7, 0.9, 1
    bezier=easeOut, 0, 0, 0.37, 1

    animation = windowsIn, 1, 1.5, easeIn
    animation = windowsOut, 1, 1.5, easeOut
    animation = windowsMove, 1, 1.5, easeOut
    animation = border, 1, 1.5, easeIn
    animation = borderangle, 1, 1.5, easeIn
    animation = fade, 1, 1.5, easeIn
    animation = workspaces, 1, 1.5, easeOut
}

dwindle {
    preserve_split = true
    force_split = 2
}

misc {
    disable_hyprland_logo = true
    mouse_move_enables_dpms = true
    key_press_enables_dpms = true
    mouse_move_focuses_monitor = false
}
