windowrule = workspace 1, match:class firefox
windowrule = float on, match:class ^(showmethekey-gtk)(.*)$
windowrule = pin on, match:class ^(showmethekey-gtk)(.*)$
windowrule = border_size 0, match:class ^(showmethekey-gtk)(.*)$
windowrule = workspace 3, match:title Telegram

windowrule = idle_inhibit fullscreen, match:fullscreen 1

windowrule = border_size 0, match:workspace w[t1]
