return {
  -- set vim options here (vim.<first_key>.<second_key> =  value)
  opt = {
    smarttab = true,
    expandtab = true,
    tabstop = 4,
    shiftwidth = 4,
    softtabstop = 4,
    relativenumber = true,
    number = true,
    spell = false,
    signcolumn = "auto",
    wrap = true,
    conceallevel = 2,
    foldenable = false,
    foldexpr = "nvim_treesitter#foldexpr()",
    foldmethod = "expr",
    linebreak = false,
    list = false,
    listchars = { tab = " ", extends = "⟩", precedes = "⟨", trail = "·", eol = "﬋" },
    showbreak = "﬌ ",
  },
  g = {
    mapleader = " ",
    autoformat_enabled = true,
    cmp_enabled = true,
    autopairs_enabled = true,
    diagnostics_enabled = true,
    status_diagnostics_enabled = true,
    icons_enabled = true,
  },
}
