theme = "gruvbox"

[editor]
mouse = true
auto-format = true
cursorline = true
line-number = "relative"
insert-final-newline = false
idle-timeout = 0
completion-trigger-len = 1
completion-timeout = 5
completion-replace = false
color-modes = true
true-color = true 
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]
rulers = [80]

[editor.file-picker]
hidden = false
git-ignore = true

[editor.indent-guides]
render = true
character = "│"
skip-levels = 1

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.lsp]
display-messages = true
display-inlay-hints = true
snippets = false

[editor.statusline]
left = ["mode", "separator", "diagnostics", "file-name", "file-modification-indicator"]
center = []
right = ["position", "file-encoding", "file-line-ending", "file-type"]
separator = " "
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
"ш" = "insert_mode"
"Ш" = "insert_at_line_start"
"ф" = "append_mode"
"Ф" = "insert_at_line_end"
"р" = "move_char_left"
"о" = "move_visual_line_down"
"л" = "move_visual_line_up"
"д" = "move_char_right"
"г" = "undo"
"Г" = "redo"
"н" = "yank"
"з" = "paste_after"
"З" = "paste_before"
"к" = "replace"
"К" = "replace_with_yanked"
"ц" = "move_next_word_start"
"и" = "move_prev_word_start"
"у" = "move_next_word_end"
"Ц" = "move_next_long_word_start"
"И" = "move_prev_long_word_start"
"У" = "move_next_long_word_end"
"а" = "find_next_char"
"е" = "find_till_char"
"А" = "find_prev_char"
"Е" = "till_prev_char"
"в" = "delete_selection"
"щ" = "open_below"
"Щ" = "open_above"
"с" = "change_selection"
"м" = "select_mode"
"ч" = "extend_line_below"

[keys.select]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
"ш" = "insert_mode"
"Ш" = "insert_at_line_start"
"ф" = "append_mode"
"Ф" = "insert_at_line_end"
"р" = "move_char_left"
"о" = "move_visual_line_down"
"л" = "move_visual_line_up"
"д" = "move_char_right"
"г" = "undo"
"Г" = "redo"
"н" = "yank"
"з" = "paste_after"
"З" = "paste_before"
"к" = "replace"
"К" = "replace_with_yanked"
"ц" = "move_next_word_start"
"и" = "move_prev_word_start"
"у" = "move_next_word_end"
"Ц" = "move_next_long_word_start"
"И" = "move_prev_long_word_start"
"У" = "move_next_long_word_end"
"а" = "find_next_char"
"е" = "find_till_char"
"А" = "find_prev_char"
"Е" = "till_prev_char"
"в" = "delete_selection"
"щ" = "open_below"
"Щ" = "open_above"
"с" = "change_selection"
"м" = "normal_mode"
"ч" = "extend_line_below"
