[language-server.clangd]
command = "clangd"
args = [
#   "--background-index",
  "--header-insertion=never",
]

[[language]]
name = "cpp"
file-types = ["cpp", "hpp", "cc", "hh"]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "c"
file-types = ["c", "h"]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "rust"

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'

[[language]]
name = "go"

[[language]]
name = "toml"
auto-format = true

[[language]]
name = "zig"
auto-format = false
