[language-server.clangd]
command = "clangd"
args = [
  "--background-index",
  "--header-insertion=never",
]

[language-server.haskell-language-server.config]
haskell = { formattingProvider = "stylish-haskell" }

[[language]]
name = "cpp"
file-types = ["cpp", "hpp", "cc", "hh"]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "c"
file-types = ["c", "h"]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "zig"
auto-format = false
language-servers = [ { name = "zls", except-features = [ "inlay-hints" ] } ]

[[language]]
name = "latex"
file-types = ["tex"]
indent = { tab-width = 4, unit = "    " }
