[language-server.clangd]
command = "clangd"
args = [
  "--background-index",
  "--header-insertion=never",
  "-j=8",
 ]

[[language]]
name = "cpp"
file-types = ["cpp", "hpp", "cc", "hh"]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "c"
file-types = ["c", "h"]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "zig"
auto-format = false
language-servers = [ { name = "zls", except-features = [ "inlay-hints" ] } ]

[[language]]
name = "latex"
file-types = ["tex"]
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "java"
scope = "source.java"
file-types = ["java"]
roots = ["pom.xml", "build.gradle", "build.gradle.kts", ".gradle", "gradlew"]
language-servers = ["jdtls"]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "scala"
file-types = ["scala", "sc", "sbt"]
language-servers = ["metals"]
indent = { tab-width = 2, unit = "  " }
