[language-server.clangd]
command = "clangd"
args = [
  "--background-index",
  "--header-insertion=never",
]

[[language]]
name = "cpp"
file-types = ["cpp", "hpp", "cc", "hh"]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "c"
file-types = ["c", "h"]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "rust"

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'

[[language]]
name = "zig"
auto-format = false
language-servers = [ { name = "zls", except-features = [ "inlay-hints" ] } ]

[[language]]
name = "haskell"
file-types = ["hs"]
formatter = { command = "stylish-haskell"}
# indent = { tab-width = 4, unit = "    " }
